export const Users = [
  {
    id: 1,
    profilePicture: "/assets/Person/1.jfif",
    username: "Miracle Okafor",
  },
  {
    id: 2,
    profilePicture: "/assets/Person/2.jfif",
    username: "chioma Okafor",
  },
  {
    id: 3,
    profilePicture: "/assets/Person/3.jfif",
    username: "Precious Okafor",
  },
  {
    id: 4,
    profilePicture: "/assets/Person/4.jfif ",
    username: "chisom Okafor",
  },
  {
    id: 5,
    profilePicture: "/assets/Person/5.jfif",
    username: "emmanuel Okafor",
  },
  {
    id: 6,
    profilePicture: "/assets/Person/7.jfif",
    username: "erere Okafor",
  },
  {
    id: 7,
    profilePicture: "/assets/Person/7.jfif",
    username: "daddy Okafor",
  },
  {
    id: 8,
    profilePicture: "/assets/Person/8.jfif",
    username: "mummy Okafor",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love for Precious",
    photo: "/assets/Post/1.jfif",
    date: "5 mins ago",
    userId: 1,
    like: 34,
    comment: 9,
  },
  {
    id: 2,
    photo: "/assets/Post/3.jfif",
    date: "5 mins ago",
    userId: 2,
    like: 34,
    comment: 9,
  },
  {
    id: 3,
    photo: "/assets/Post/2.jfif",
    date: "5 mins ago",
    userId: 3,
    like: 34,
    comment: 9,
  },
  {
    id: 4,
    photo: "/assets/Post/4.jfif",
    date: "5 mins ago",
    userId: 4,
    like: 34,
    comment: 9,
  },
  {
    id: 5,
    photo: "/assets/Post/5.jfif",
    date: "5 mins ago",
    userid: 5,
    like: 34,
    comment: 9,
  },
  {
    id: 6,
    photo: "/assets/Post/6.jfif",
    date: "5 mins ago",
    userId: 6,
    like: 34,
    comment: 9,
  },
  {
    id: 7,
    desc: "Love for Precious",
    photo: "/assets/Post/5.jfif",
    date: "5 mins ago",
    userId: 7,
    like: 34,
    comment: 9,
  },
  {
    id: 8,
    photo: "/assets/Post/4.jfif",
    date: "5 mins ago",
    userId: 8,
    like: 34,
    comment: 9,
  },
  {
    id: 10,
    photo: "/assets/Post/3.jfif",
    date: "5 mins ago",
    userId: 9,
    like: 34,
    comment: 9,
  },
  {
    id: 11,
    photo: "/assets/Post/2.jfif",
    date: "5 mins ago",
    userId: 10,
    like: 34,
    comment: 9,
  },
  {
    id: 12,
    photo: "/assets/Post/1.jfif",
    date: "5 mins ago",
    userId: 11,
    like: 34,
    comment: 9,
  },
];
